
version: '3'
services:

   jupyter:
      build:    .
      image:    jaeo/datathon-webarchives
      environment:
         SPARK_PUBLIC_DNS: localhost
         PYSPARK_DRIVER_PYTHON: start-notebook.sh
         # uncomment to remove the need of a token to connect
         # DOCKER_STACKS_JUPYTER_CMD: lab --NotebookApp.token=''
      ports:
         - 8888:8888  # Jupyter 
         - 4040:4040  # SparkContext webUI
      volumes:
         - ./notebooks:/content/notebooks
         - ./scripts:/content/scripts
